version: '3.8'
services:
  mysql:
    image: mysql:8.0.35
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data:/var/lib/mysql"
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  postgres:
    image: "public.ecr.aws/bitnami/postgresql:12.7.0"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: root
volumes:
  mysql_data:
  postgres_data:
