name: Build
on: 
  push:
    branches:
    - main
  workflow_dispatch:
  pull_request:
permissions:
  contents: read

jobs:
  Build-and-Test-CDK:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: |
          npm ci
          npm run build
          npm run test
  Build-and-Test-Application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: |
          npm ci
          npm run build
        working-directory: ./backend
